# MariaDB setting
server:
  port: 8081

spring:
  sql:
    init:
      platform: mariadb
      encoding: UTF-8
      mode: always
  datasource:
    url: jdbc:mariadb://192.168.0.15:3306/encorebbs
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: gur0215
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html



    mybatis:
      type-aliases-package: com.encore.bbs

# mybatis mapping
# mapper.xml location
mybatis:
  config-location: classpath:/mybatis-config.xml
  mapper-locations: classpath:/mapper/*.xml

